### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by akshatgit** [secure-software-engineering/COVA#15]
I'm trying to build the project install using the docker image built from [this](https://github.com/secure-software-engineering/COVA/blob/master/cova/config/Dockerfile.txt) dockerfile. 

Steps were taken to build:
- Built the Z3 docker image
- Cloned the repo and mounted source repo inside the docker image, using this command: 
`docker run -it -v $(pwd):/mnt cova:test /bin/bash`
- Installed the dependencies inside the docker: 
`root@xyz:/mnt/cova# localLibs/install_local_libs.sh`
- Ran mvn install:
`root@xyz:/mnt/cova# mvn install`

I am getting the following error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.538 s
[INFO] Finished at: 2021-07-06T22:06:47Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cova: Could not resolve dependencies for project de.upb.swt:cova:jar:0.0.1-SNAPSHOT: Could not find artifact de.upb.swt:constraintBench:jar:0.0.1-SNAPSHOT in soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Are these steps correct or am I missing any steps?

Thanks for all the help!
-Akshat

**Comment by linghuiluo** [comment]
@akshatgit did you execute mvn install from the root directory of cova? constraintBench is the submodule that should be built together. If that is not the problem.
Can you try to bind Z3 by yourself? See https://github.com/secure-software-engineering/COVA#1-bind-z3-library
I haven't tested the docker image recently.

**Comment by linghuiluo** [comment]
@swissiety Can you take a look at the docker image?

**Comment by swissiety** [comment]
Those were the steps i just did to compile the project successfully in a docker container. 
1. `docker build -t cova:test ./cova/config/` to build the [docker image](/cova/config/Dockerfile).
2. `docker run -it -v $(pwd):/mnt cova:test /bin/bash` to mount the container and open the container shell.
3. `git clone https://github.com/secure-software-engineering/COVA.git && cd COVA` to clone the repo into the docker container.
4. `./cova/localLibs/install_local_libs.sh` to install required libraries.
5. `mvn install` to build the project and its submodules (constraintbench & cova) .

**Comment by akshatgit** [comment]
Thanks @swissiety for  the quick reply, I was running `mvn install` from `./cova` directory. 

I'm now at the root directory. 
```
root@xyz:/mnt# ls
LICENSE.txt  README.md	_config.yml  constraintBench  cova  cova-logo.PNG  cova_logo.pdf  longversion.pdf  pom.xml
```
But now I'm getting a different error from `mvn install`:
```
[main] INFO cova.core.RuleManager - Fri Jul 09 07:09:17 UTC 2021
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.898 s <<< FAILURE! - in constraintBenchTestSuite.androidApp.SingleIfBranchTest
[ERROR] testSingleIfBranch1(constraintBenchTestSuite.androidApp.SingleIfBranchTest)  Time elapsed: 3.898 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native

[INFO] Running unitTestSuite.testCore.ConstraintFactoryTest
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in unitTestSuite.testCore.ConstraintFactoryTest
[ERROR] testCreateConstraintFromSourceTaints1(unitTestSuite.testCore.ConstraintFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testCore.ConstraintFactoryTest.<init>(ConstraintFactoryTest.java:43)

[ERROR] testCreateConstraintFromSourceTaints2(unitTestSuite.testCore.ConstraintFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testCore.ConstraintFactoryTest.<init>(ConstraintFactoryTest.java:43)

[ERROR] testCreateConstraintFromSourceTaints3(unitTestSuite.testCore.ConstraintFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testCore.ConstraintFactoryTest.<init>(ConstraintFactoryTest.java:43)

[ERROR] testCreateConstraintFromSourceTaints4(unitTestSuite.testCore.ConstraintFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testCore.ConstraintFactoryTest.<init>(ConstraintFactoryTest.java:43)

[ERROR] testCreateConstraintFromSourceTaints5(unitTestSuite.testCore.ConstraintFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testCore.ConstraintFactoryTest.<init>(ConstraintFactoryTest.java:43)

[INFO] Running unitTestSuite.testData.ConstraintZ3Test
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in unitTestSuite.testData.ConstraintZ3Test
[ERROR] test01(unitTestSuite.testData.ConstraintZ3Test)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at unitTestSuite.testData.ConstraintZ3Test.test01(ConstraintZ3Test.java:28)

[INFO] Running unitTestSuite.testData.WrappedAccessPathTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in unitTestSuite.testData.WrappedAccessPathTest
[INFO] Running unitTestSuite.testRunner.AndroidApkAnalyzerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in unitTestSuite.testRunner.AndroidApkAnalyzerTest
[INFO] Running unitTestSuite.testRunner.JavaAppAnalyzerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in unitTestSuite.testRunner.JavaAppAnalyzerTest
[INFO] Running unitTestSuite.testSourceData.FieldTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in unitTestSuite.testSourceData.FieldTest
[INFO] Running unitTestSuite.testSourceData.MethodTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in unitTestSuite.testSourceData.MethodTest
[INFO] Running unitTestSuite.testSourceData.SourceFieldTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in unitTestSuite.testSourceData.SourceFieldTest
[INFO] Running unitTestSuite.testSourceData.SourceMethodTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in unitTestSuite.testSourceData.SourceMethodTest
[INFO] Running unitTestSuite.testSourceData.SourceUICallbackTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in unitTestSuite.testSourceData.SourceUICallbackTest
[INFO] Running unitTestSuite.testSourceParser.SourceParserTest
[main] INFO cova.source.parser.SourceParser - Read 451 APIs from /mnt/cova/config/Configuration_APIs.txt
[main] INFO cova.source.parser.SourceParser - Read 451 APIs from /mnt/cova/config/Configuration_APIs.txt
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in unitTestSuite.testSourceParser.SourceParserTest
[INFO] Running unitTestSuite.testSourceParser.UICallbackParserTest
[main] INFO cova.source.parser.UICallbackParser - Read 336 APIs from /mnt/cova/config/UICallback_APIs.txt
[main] INFO cova.source.parser.UICallbackParser - Read 336 APIs from /mnt/cova/config/UICallback_APIs.txt
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in unitTestSuite.testSourceParser.UICallbackParserTest
[INFO] Running unitTestSuite.testSymbolic.SymbolicNameManagerTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in unitTestSuite.testSymbolic.SymbolicNameManagerTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ArgumentToParameter1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » UnsatisfiedLink
[ERROR]   BooleanMultiple1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanMultiple2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanMultiple3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanMultiple4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanMultiple5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanMultiple6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   BooleanSingle8Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Callback1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   DoubleSingle1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple10Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple11Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple12Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple8Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseMultiple9Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   ImpreciseSingle7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IndirectConcrete1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IndirectConcrete2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IndirectConcrete3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IndirectConcrete4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Infeasible1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Infeasible2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InstanceField8Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IntegerMultiple1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   IntegerMultiple2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterMultiple1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterMultiple2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle6Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   InterSingle7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   LookUpSwitchStmt1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Loop1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Loop2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Loop3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Loop4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Loop5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Mixed1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   NonPrimSingle1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   NonPrimSingle2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   NonPrimSingle3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   PrimitiveFieldRef1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   PrimitiveFieldRef2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   PrimitiveType1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Recursion1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField2Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField3Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField4Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField5Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StaticField7Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   StringLiteral1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   TableSwitchStmt1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   TryBlock1Test>ConstraintBenchTestFramework.beforeTestCaseExecution:105->ConstraintBenchTestFramework.analyze:145 » NoClassDefFound
[ERROR]   Callbacks1Test>ConstraintBenchTestFrameworkForAndroidApp.beforeTestCaseExecution:57 » NoClassDefFound
[ERROR]   SingleIfBranchTest>ConstraintBenchTestFrameworkForAndroidApp.beforeTestCaseExecution:57 » NoClassDefFound
[ERROR]   ConstraintFactoryTest.<init>:43 » NoClassDefFound Could not initialize class c...
[ERROR]   ConstraintFactoryTest.<init>:43 » NoClassDefFound Could not initialize class c...
[ERROR]   ConstraintFactoryTest.<init>:43 » NoClassDefFound Could not initialize class c...
[ERROR]   ConstraintFactoryTest.<init>:43 » NoClassDefFound Could not initialize class c...
[ERROR]   ConstraintFactoryTest.<init>:43 » NoClassDefFound Could not initialize class c...
[ERROR]   ConstraintZ3Test.test01:28 » NoClassDefFound Could not initialize class com.mi...
[INFO]
[ERROR] Tests run: 136, Failures: 0, Errors: 92, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] cova-root 0.0.1-SNAPSHOT ........................... SUCCESS [  0.100 s]
[INFO] constraintBench .................................... SUCCESS [ 15.210 s]
[INFO] cova 0.0.1-SNAPSHOT ................................ FAILURE [02:14 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:29 min
[INFO] Finished at: 2021-07-09T07:09:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project cova: There are test failures.
[ERROR]
[ERROR] Please refer to /mnt/cova/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cova
```

**Comment by linghuiluo** [comment]
@akshatgit This error happens when you didn't bind z3 properly. Are you on mac? If it is the case, can you set an environment variable `DYLD_LIBRARY_PATH` in your IDE for the tests to `path-to-your-local-z3/bin` as the readme says? Then you should be able to execute the tests in your IDE. Unfortunately, on mac  DYLD_LIBRARY_PATH is not possible unless System Integrity Protection (SIP) is disabled, so mvn doesn't work properly. But on windows or linux, mvn should work perfectly if you bind z3 as the readme says.

**Comment by akshatgit** [comment]
Yes, I'm on a mac. So the docker method to build the jar will not work? I'm not familiar with Z3 and  DYLD_LIBRARY_PATH. I can switch to Linux if I can build using the docker environment.

**Comment by linghuiluo** [comment]
@akshatgit yes, the docker image was for linux.

**Comment by akshatgit** [comment]
Ok, thanks for all the help. I'll try it on a Linux machine.

**Comment by swissiety** [comment]
but as far as i understand the concept of docker containers executing things inside the container should work regardless of the host machine (as thats the main design goal) so the container method should work on a mac, too? I just didn't test/verify it due to the lack of a mac/windows machine.

**Comment by linghuiluo** [comment]
@akshatgit Is your problem resolved?

**Comment by akshatgit** [comment]
@linghuiluo Yes, we can close this issue. Thanks!
